name: Basic infra pipeline

on: push


jobs:
    initial_job:
        runs-on: ubuntu-latest
        steps: 
            - name: code checkout
              uses: actions/checkout@v4

            - name: terraform version setup
              uses: hashicorp/setup-terraform@v2
              with: 
                terraform_version: 1.7

            - name: aws configuration 
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                aws_region: "us-east-1"

            - name: terraform initialization
              id: init
              run: terraform init

            - name: terraform validation
              id: validate
              run: terraform validate

            - name: terraform fmt
              id: fmt
              run: terraform fmt

            - name: terraform plan
              id: plan
              run: terraform plan
              


            - name: terraform apply
              id: apply
              run: terraform apply
            

